version: "3.4"
services:
  sepolia-beacon:
    image: sigp/lighthouse:latest
    command: ["/start.sh"]
    ports:
      - 30352:5052/tcp
      - 30353:5053/tcp
      - 30354:5054/tcp     # metrics endpoint
      - 30300:9000/tcp
      - 30300:9000/udp
    volumes:
      - ./start-beacon.sh:/start.sh
      - ./lib/beacon:/root/.lighthouse
      - ./lib/sepolia/geth/jwtsecret:/secrets/jwt.hex
      - ./log:/var/log/sepolia
    restart: on-failure
    stop_grace_period: 3m

  node-sepolia:
    image: ethereum/client-go:latest
    container_name: node-sepolia
    entrypoint: /bin/sh
    command: ["/start.sh"]
    ports:
      - 30301:8545
      - 30303:30303/udp
      - 30303:30303/tcp
    expose:
      - 8551
    volumes:
      - ./start-geth.sh:/start.sh
      - ./lib/sepolia:/var/lib/sepolia
      - ./log:/var/log/sepolia
    restart: on-failure
    stop_grace_period: 3m

  op-geth:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101315.1
    restart: unless-stopped
    stop_grace_period: 5m
    entrypoint: /scripts/start-op-geth.sh
    env_file:
      - ./envs/${NETWORK_NAME}/op-geth.env
      - .env
    volumes:
      - ./envs/${NETWORK_NAME}/config:/chainconfig
      - ./scripts/:/scripts
      - shared:/shared
      - op_geth:/geth
    ports:
      - ${PORT__OP_GETH_HTTP:-9993}:8545
      - ${PORT__OP_GETH_WS:-9994}:8546
      - ${PORT__OP_GETH_P2P:-39393}:${PORT__OP_GETH_P2P:-39393}/udp
      - ${PORT__OP_GETH_P2P:-39393}:${PORT__OP_GETH_P2P:-39393}/tcp
    extra_hosts:
      - "host.docker.internal:host-gateway"

  op-node:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.7.7-rc.1
    restart: unless-stopped
    stop_grace_period: 5m
    entrypoint: /scripts/start-op-node.sh
    env_file:
      - ./envs/${NETWORK_NAME}/op-node.env
      - .env
    volumes:
      - ./envs/${NETWORK_NAME}/config:/chainconfig
      - ./scripts/:/scripts
      - shared:/shared
    ports:
      - ${PORT__OP_NODE_P2P:-9003}:9003/udp
      - ${PORT__OP_NODE_P2P:-9003}:9003/tcp
      - ${PORT__OP_NODE_HTTP:-9545}:9545
    extra_hosts:
      - "host.docker.internal:host-gateway"

  bedrock-init:
    build:
      context: ./docker/dockerfiles
      dockerfile: Dockerfile.bedrock-init
    entrypoint: /scripts/init-bedrock.sh
    env_file:
      - ./envs/${NETWORK_NAME}/op-geth.env
      - .env
    volumes:
      - ./scripts/:/scripts
      - shared:/shared
      - op_geth:/geth
      - l2geth:/legacy-geth
      - torrent_downloads:/downloads

volumes:
  dtl:
  l2geth:
  shared:
  op_geth:
  torrent_downloads:
